# =========================
# GENERAL
# =========================
allow_remote_control yes
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0
disable_ligatures never

# =========================
# CURSOR
# =========================

cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# цвет курсора будет из theme.conf

# =========================
# WINDOW
# =========================

window_padding_width 15
window_margin_width 0

background_opacity 0.95
dynamic_background_opacity yes

# плавный ресайз
resize_debounce_time 0.1

# =========================
# SCROLL
# =========================

scrollback_lines 10000
wheel_scroll_multiplier 5.0

# =========================
# TABS
# =========================

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled

tab_title_template "{index}: {title}"

# =========================
# MOUSE
# =========================

mouse_hide_wait 3.0

# =========================
# PERFORMANCE
# =========================

repaint_delay 10
input_delay 3

# =========================
# KEYBINDS
# =========================

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+enter new_window
map ctrl+shift+w close_window

map ctrl+shift+left previous_window
map ctrl+shift+right next_window

map ctrl+shift+t new_tab
map ctrl+shift+q close_tab

# =========================
# THEME (ВАЖНО)
# =========================

include theme.conf
