# Generated by betterdeb theme system — do not edit directly

[Settings]
gtk-theme-name=${gtk_theme}
gtk-icon-theme-name=${gtk_icon_theme}
gtk-font-name=JetBrains Mono 11
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1
gtk-button-images=0
gtk-menu-images=0
