# Generated by betterdeb theme system — do not edit directly

$$bg      = rgb(${bg_hex})
$$fg      = rgb(${fg_hex})
$$accent  = rgb(${accent_hex})
$$border  = rgb(${border_hex})
$$red     = rgb(${red_hex})
$$green   = rgb(${green_hex})
$$yellow  = rgb(${yellow_hex})
$$blue    = rgb(${blue_hex})
$$purple  = rgb(${purple_hex})
$$bg_win  = rgb(${bg_window_hex})
$$bg_pnl  = rgb(${bg_panel_hex})

general {
    col.active_border   = rgb(${border_hex}) rgb(${accent_hex}) 45deg
    col.inactive_border = rgb(${bg_window_hex})
}

decoration {
    col.shadow = rgba(${shadow_hex})
}
