# Generated by betterdeb theme system — do not edit directly

font_family      JetBrains Mono
font_size        12.0

cursor           ${accent}
cursor_trail     3

background          ${bg}
foreground          ${fg}
background_opacity  0.95

selection_background ${accent}
selection_foreground ${bg}

# Normal colors
color0  ${bg}
color1  ${red}
color2  ${green}
color3  ${yellow}
color4  ${blue}
color5  ${purple}
color6  ${cyan}
color7  ${fg_dim}

# Bright colors
color8  ${bg_window}
color9  ${red}
color10 ${green}
color11 ${yellow}
color12 ${blue}
color13 ${purple}
color14 ${cyan}
color15 ${fg}

window_padding_width 15
