/* Generated by betterdeb theme system — do not edit directly */

* {
    bg:       ${bg};
    bg-alt:   ${bg_window};
    bg-menu:  ${bg_menu};
    fg:       ${fg};
    fg-dim:   ${fg_dim};
    accent:   ${accent};
    border-c: ${border};
    red:      ${red};
    green:    ${green};

    background-color: transparent;
    text-color:       @fg;
    font:             "JetBrainsMono Nerd Font 12";
}

window {
    width:            520px;
    background-color: @bg;
    border:           2px solid;
    border-color:     @border-c;
    border-radius:    14px;
    padding:          6px;
}

mainbox {
    background-color: transparent;
    children:         [inputbar, listview];
    spacing:          6px;
    padding:          6px;
}

inputbar {
    background-color: @bg-alt;
    border-radius:    10px;
    padding:          8px 14px;
    children:         [prompt, entry];
    spacing:          8px;
}

prompt {
    text-color:       @accent;
    font:             "JetBrainsMono Nerd Font Bold 12";
}

entry {
    placeholder:       "Search...";
    placeholder-color: @fg-dim;
}

listview {
    background-color: transparent;
    columns:          1;
    lines:            9;
    spacing:          3px;
    scrollbar:        false;
    fixed-height:     true;
}

element {
    background-color: transparent;
    border-radius:    8px;
    padding:          7px 12px;
    orientation:      horizontal;
    spacing:          10px;
}

element selected {
    background-color: @bg-alt;
    text-color:       @accent;
}

element-icon {
    background-color: transparent;
    size:             1.2em;
}

element-text {
    background-color: transparent;
    text-color:       inherit;
    vertical-align:   0.5;
}

message {
    padding:          6px;
}

textbox {
    text-color: @fg-dim;
    padding:    4px 12px;
}
