# Generated by betterdeb theme system — do not edit directly

set $$bg     ${bg}
set $$fg     ${fg}
set $$accent ${accent}
set $$red    ${red}
set $$bg_alt ${bg_window}

client.focused          $$accent $$accent $$fg     $$accent $$accent
client.focused_inactive $$bg_alt $$bg_alt $$fg_dim $$bg_alt $$bg_alt
client.unfocused        $$bg_alt $$bg_alt $$fg_dim $$bg_alt $$bg_alt
client.urgent           $$red    $$red    $$fg     $$red    $$red
