/* Generated by betterdeb theme system — do not edit directly */

@define-color bg        ${bg};
@define-color bg_panel  ${bg_panel};
@define-color bg_window ${bg_window};
@define-color bg_menu   ${bg_menu};
@define-color fg        ${fg};
@define-color fg_dim    ${fg_dim};
@define-color red       ${red};
@define-color green     ${green};
@define-color yellow    ${yellow};
@define-color blue      ${blue};
@define-color purple    ${purple};
@define-color cyan      ${cyan};
@define-color orange    ${orange};
@define-color border    ${border};
@define-color accent    ${accent};

/* Derived variables for waybar modules */
@define-color module-bg    ${module_bg};
@define-color tooltip-bg   ${bg_panel};
@define-color inactive     ${fg_dim};
@define-color workspace-fg ${fg};
