/* Generated by betterdeb theme system — do not edit directly */

@define-color bg        ${bg};
@define-color bg_window ${bg_window};
@define-color fg        ${fg};
@define-color fg_dim    ${fg_dim};
@define-color accent    ${accent};
@define-color border    ${border};
